"use client";

import { motion } from "motion/react";
import { useState } from "react";

/**
 * "Explain this card" — the generative half of the scan.
 *
 * WHY IT IS A BUTTON AND NOT AUTOMATIC, and there are three separate reasons
 * that happen to agree:
 *
 *   it is metered — free, on Groq's free tier, but a free allowance is a
 *                ceiling and it should not be spent on a card somebody scanned
 *                by accident
 *   it is slow — the match is 70 ms and this is TEN TO TWELVE SECONDS, measured
 *                on real cards; running it automatically would make every
 *                identification feel that slow
 *   it is not always wanted — somebody cataloguing forty cards wants the
 *                identification and nothing else, forty times over
 *
 * WHY THE FACTS ARE SHOWN. This is the first thing on the site a reader has any
 * reason to distrust: everything else is a measurement or a record, and this is
 * a model writing sentences. The sheet it was given folds open underneath, so
 * "where did that number come from" is one tap rather than an act of faith. It
 * is also how a wrong answer gets diagnosed — if the figure is wrong ON the
 * sheet, the fault is ours and not the model's.
 */

type Printing = {
  finish?: string;
  origin: string;
  rarity?: string;
  cardmarketEur?: number;
  tcgplayerUsd?: number;
};

type Facts = {
  game: string;
  name: string;
  code: string;
  priceNote: string;
  printings: Printing[];
  context?: {
    set?: { name: string; releaseDate?: string; cardCount?: number };
    standing?: { rank: number; outOf: number; setLowEur: number; setMedianEur: number; setHighEur: number };
    history?: { date: string; eur?: number }[];
  };
  graded?: {
    languages: string[];
    rows: { condition: string; cells: Record<string, { median?: number; currency?: string; count?: number }> }[];
    psa10Multiple: Record<string, number>;
    note: string;
  };
};

/**
 * Every eBay reading that went into the answer, as a table.
 *
 * THE WHOLE TABLE, NOT A SUMMARY. An earlier version kept only PSA 10 and raw
 * and dropped PSA 9 and PSA 8 — which is throwing away evidence to save four
 * lines. This block is the eBay counterpart of "what it was told": its job is
 * to let a reader check the sentences above against the numbers behind them,
 * and a summary cannot do that.
 *
 * TIERS DOWN, LANGUAGES ACROSS, because the comparison a collector actually
 * makes is between conditions of the same card, and a column is read faster
 * than a row. Japanese beside English in the same row makes the other
 * comparison — the two markets for one card — free.
 *
 * THE COUNT IS SHOWN under each figure. A median of two asks is not a market,
 * and a bare price gives the reader no way to tell that from a median of sixty.
 *
 * IT SCROLLS SIDEWAYS RATHER THAN WRAPPING. Two languages fit a phone; a third
 * would not, and a table that reflows into unreadable columns is worse than one
 * that admits it is wider than the screen.
 */
/**
 * WHO SAID THIS — the one element the whole panel is organised around.
 *
 * The brief was "mark clearly what's coming from the AI and what's coming from
 * other things like eBay", and the honest reading of that is that provenance is
 * not a footnote on this screen, it is the primary axis. A price measured from
 * a marketplace and a sentence generated by a model are different KINDS of
 * claim, and a reader who cannot tell them apart at a glance is being asked to
 * trust both equally.
 *
 * So every block on this panel wears one of these, and the three are visually
 * unmistakable rather than three shades of grey:
 *
 *   WRITTEN BY AI   yellow on black — the one thing here that can be wrong
 *   MEASURED        green — our files, our arithmetic, reproducible
 *   LIVE MARKET     blue — fetched from eBay just now, true when fetched
 *   OUTSIDE         blue outline — the open web, unverifiable by us
 *
 * BLACK FOR THE AI ONE, deliberately the loudest. Every other source on this
 * page is a record; that one is a sentence somebody's model wrote, and it
 * should be the easiest thing on screen to identify.
 */
type Source = "ai" | "measured" | "market" | "outside";

const SOURCE_STYLE: Record<Source, { label: string; className: string; style?: React.CSSProperties }> = {
  ai: {
    label: "Written by AI",
    className: "text-[9px] font-black uppercase tracking-[0.08em]",
    style: { background: "var(--nav-dark)", color: "var(--pokemon-yellow)" },
  },
  measured: {
    label: "Measured",
    className: "text-[9px] font-black uppercase tracking-[0.08em]",
    style: { background: "var(--success-green)", color: "#06331a" },
  },
  market: {
    label: "Live market",
    className: "text-[9px] font-black uppercase tracking-[0.08em]",
    style: { background: "var(--pokemon-blue)", color: "#ffffff" },
  },
  outside: {
    label: "Outside our records",
    className: "text-[9px] font-black uppercase tracking-[0.08em]",
    style: { background: "transparent", color: "var(--pokemon-blue)", border: "2px solid var(--pokemon-blue)" },
  },
};

function Tag({ source, note }: { source: Source; note?: string }) {
  const tone = SOURCE_STYLE[source];
  return (
    <div className="flex flex-wrap items-center gap-2">
      <span className={`rounded px-2 py-1 ${tone.className}`} style={tone.style}>
        {tone.label}
      </span>
      {note ? <span className="text-[11px] font-bold text-muted-text">{note}</span> : null}
    </div>
  );
}

function Graded({ graded }: { graded: NonNullable<Facts["graded"]> }) {
  const money = (cell?: { median?: number; currency?: string }) =>
    cell?.median === undefined ? "—" : `${cell.currency ?? ""} ${cell.median.toFixed(2)}`.trim();

  return (
    <div className="mt-3 border-t border-black/15 pt-2.5">
      <div className="flex items-baseline justify-between gap-2">
        <span className="text-[10px] font-black uppercase tracking-wide text-muted-text">Asking on eBay now</span>
        {Object.entries(graded.psa10Multiple).map(([language, multiple]) => (
          <span key={language} className="shrink-0 text-[10px] font-black">
            PSA 10 = {multiple}x raw
            {graded.languages.length > 1 ? ` (${language.slice(0, 2).toUpperCase()})` : ""}
          </span>
        ))}
      </div>

      <div className="mt-1.5 overflow-x-auto">
        <table className="w-full text-[11px]">
          <thead>
            <tr className="text-left text-muted-text">
              <th className="pb-1 pr-2 font-black uppercase tracking-wide">Grade</th>
              {graded.languages.map((language) => (
                <th key={language} className="pb-1 pl-2 text-right font-black uppercase tracking-wide">
                  {language}
                </th>
              ))}
            </tr>
          </thead>
          <tbody>
            {graded.rows.map((row) => (
              <tr key={row.condition} className="border-t border-muted-surface">
                <td className="py-1 pr-2 font-black">{row.condition}</td>
                {graded.languages.map((language) => {
                  const cell = row.cells[language];
                  return (
                    <td key={language} className="py-1 pl-2 text-right tabular-nums">
                      {money(cell)}
                      {cell?.count ? (
                        <span className="block text-[9px] font-normal text-muted-text">{cell.count} listed</span>
                      ) : null}
                    </td>
                  );
                })}
              </tr>
            ))}
          </tbody>
        </table>
      </div>

      <p className="mt-1.5 text-[10px] leading-relaxed text-muted-text">{graded.note}</p>
    </div>
  );
}

function Figures({ facts }: { facts: Facts }) {
  const priced = facts.printings.filter((p) => p.cardmarketEur !== undefined || p.tcgplayerUsd !== undefined);
  const standing = facts.context?.standing;
  const history = (facts.context?.history ?? []).filter((h) => typeof h.eur === "number");

  // THE SPREAD, not each printing's price — the printings are listed below in
  // full. What a glance needs is whether the versions differ enough to matter,
  // and measured across the catalogue 60.3% of priced cards differ by a median
  // 3.45x, so the multiple is the number that carries.
  const eur = priced.map((p) => p.cardmarketEur).filter((v): v is number => v !== undefined);
  const spread = eur.length > 1 ? Math.max(...eur) / Math.min(...eur) : undefined;

  const first = history[0]?.eur;
  const last = history[history.length - 1]?.eur;
  const moved = first !== undefined && last !== undefined && first !== 0 ? (last - first) / first : undefined;

  const cells: { label: string; value: string; tone?: "up" | "down" }[] = [];

  const headline = priced[0];
  if (headline?.cardmarketEur !== undefined) {
    cells.push({ label: "Cardmarket", value: `EUR ${headline.cardmarketEur.toFixed(2)}` });
  }
  if (headline?.tcgplayerUsd !== undefined) {
    cells.push({ label: "TCGplayer", value: `USD ${headline.tcgplayerUsd.toFixed(2)}` });
  }
  if (standing) {
    cells.push({ label: "In its set", value: `#${standing.rank} of ${standing.outOf}` });
  }
  if (spread !== undefined && spread >= 1.05) {
    cells.push({ label: "Printings differ", value: `${spread.toFixed(1)}x` });
  }
  if (moved !== undefined) {
    cells.push({
      label: history.length > 1 ? `Since ${history[0].date}` : "Last reading",
      // ZERO IS SAID AS "no change", not as "0.0%". A percentage of nothing
      // reads like a measurement failed; the words say the reading held.
      value: moved === 0 ? "no change" : `${moved > 0 ? "+" : ""}${(moved * 100).toFixed(1)}%`,
      tone: moved === 0 ? undefined : moved > 0 ? "up" : "down",
    });
  }

  if (cells.length === 0) return null;

  return (
    <ul
      className="grid gap-1.5"
      style={{ gridTemplateColumns: "repeat(auto-fit, minmax(88px, 1fr))" }}
    >
      {cells.map((cell) => (
        <li key={cell.label} className="min-w-0">
          <div className="truncate text-[9px] font-black uppercase tracking-wide text-muted-text">{cell.label}</div>
          <div
            className="truncate text-[14px] font-black tabular-nums"
            style={cell.tone === "up" ? { color: "#1d7a4f" } : cell.tone === "down" ? { color: "#a32d2d" } : undefined}
          >
            {cell.value}
          </div>
        </li>
      ))}
    </ul>
  );
}

type State =
  | { phase: "idle" }
  | { phase: "asking" }
  | { phase: "done"; text: string; facts: Facts; web?: string }
  | { phase: "failed"; reason: string };

/**
 * The model is asked for bold headings and paragraphs, and gets markdown.
 *
 * A PARSER RATHER THAN A LIBRARY, because the shape is fixed by the prompt:
 * `**heading**` on its own line, then prose. Pulling in a markdown renderer to
 * read three bold lines would ship a parser for a grammar nothing here emits,
 * and it would also render whatever ELSE a model decided to write — links,
 * images, HTML — which is a much wider door than this needs.
 *
 * Anything that is not a heading renders as plain text, so a model that ignores
 * the format produces something readable rather than something broken.
 */
function Rendered({ text }: { text: string }) {
  return (
    <div className="grid gap-3">
      {text
        .split(/\n{2,}/)
        .map((block) => block.trim())
        .filter(Boolean)
        .map((block, index) => {
          const heading = /^\*\*(.+?)\*\*\s*(?:—|-|:)?\s*([\s\S]*)$/.exec(block);
          if (!heading) {
            return (
              <p key={index} className="text-[14px] leading-[1.6]">
                {block}
              </p>
            );
          }
          return (
            <div key={index}>
              <div className="text-[10px] font-black uppercase tracking-[0.08em] text-muted-text">{heading[1]}</div>
              <p className="mt-1 text-[14px] leading-[1.6]">{heading[2]}</p>
            </div>
          );
        })}
    </div>
  );
}

export function CardExplainer({ tcg, code }: { tcg: "pokemon" | "onepiece"; code: string }) {
  const [state, setState] = useState<State>({ phase: "idle" });

  async function ask() {
    setState({ phase: "asking" });
    try {
      const response = await fetch("/api/scan/explain", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ tcg, code }),
      });
      const payload = (await response.json().catch(() => ({}))) as {
        text?: string;
        facts?: Facts;
        web?: string;
        error?: string;
      };
      if (!response.ok || !payload.text || !payload.facts) {
        setState({ phase: "failed", reason: payload.error ?? `The explainer returned ${response.status}.` });
        return;
      }
      setState({ phase: "done", text: payload.text, facts: payload.facts, web: payload.web });
    } catch {
      setState({ phase: "failed", reason: "Could not reach the explainer. Check your connection." });
    }
  }

  if (state.phase === "idle" || state.phase === "failed") {
    return (
      <div className="mt-4 border-t-2 border-foreground pt-4">
        <Tag source="ai" note="Written only from your own records" />
        <div
          className="mt-3 flex flex-wrap items-center justify-between gap-4 rounded-md border-2 border-dashed p-4"
          style={{
            borderColor: "var(--border-subtle)",
            // The hatch is the mockup's, and it reads as "nothing here yet"
            // without needing a sentence to say so.
            background:
              "repeating-linear-gradient(45deg, var(--card-surface) 0 10px, var(--muted-surface) 10px 20px)",
          }}
        >
          <p className="flex-1 basis-60 text-[13px] font-bold leading-5 text-muted-text">
            Read this card back in plain language — which printing you are holding, where it sits in the set,
            and what the market is asking for it.
          </p>
          <motion.button
            type="button"
            onClick={ask}
            whileHover={{ y: -2 }}
            whileTap={{ y: 1, boxShadow: "1px 1px 0 0 #000" }}
            transition={{ type: "spring", stiffness: 500, damping: 30 }}
            className="whitespace-nowrap rounded-md border-2 border-foreground px-5 py-3 text-sm font-black tracking-[-0.2px] text-white"
            style={{ background: "var(--pokemon-red)", boxShadow: "4px 4px 0 0 #000" }}
          >
            Explain this card →
          </motion.button>
        </div>
        {state.phase === "failed" ? (
          <p className="mt-2 text-[11px] text-muted-text">{state.reason}</p>
        ) : null}
      </div>
    );
  }

  if (state.phase === "asking") {
    return (
      <div className="mt-4 border-t-2 border-foreground pt-4">
        <Tag source="ai" note="Written only from your own records" />
        <div
          className="mt-3 rounded-md border-2 border-dashed p-4"
          style={{ borderColor: "var(--border-subtle)" }}
        >
          <span className="flex items-center gap-2 text-[11px] font-black uppercase tracking-[0.08em] text-muted-text">
            <span
              className="h-2 w-2 rounded-full"
              style={{ background: "var(--pokemon-red)", animation: "livepulse 1s ease-in-out infinite" }}
            />
            Reading your records
          </span>
          {/* THREE BARS, NOT A SPINNER. A spinner says "wait"; a shape that
              looks like the paragraph about to arrive says what is coming, and
              the wait stops feeling like a stall. */}
          {[88, 96, 64].map((width, index) => (
            <motion.span
              key={width}
              className="mt-2 block h-3 rounded-sm"
              style={{ width: `${width}%`, background: "var(--muted-surface)" }}
              animate={{ opacity: [0.45, 1, 0.45] }}
              transition={{ duration: 1.2, repeat: Infinity, delay: index * 0.15 }}
            />
          ))}
        </div>
      </div>
    );
  }

  return (
    /* PROVENANCE IS THE LAYOUT, which is the whole point of this redesign.
       Asked for as "mark clearly what's coming from the AI and what's coming
       from other things like eBay", and the honest reading is that a price
       measured from a marketplace and a sentence a model wrote are different
       kinds of claim — so they get different grounds, different tags, and are
       never allowed to blend into one another.

       Four blocks, four sources, in descending order of how much a reader
       should trust them without checking:

         MEASURED     our snapshot and our arithmetic, reproducible
         LIVE MARKET  eBay, fetched seconds ago, true when fetched
         WRITTEN BY AI  the one thing here that can be wrong
         OUTSIDE      the open web, unverifiable by us

       The AI block is NOT first despite being the headline. Sentences read
       faster than tables, so putting them on top means they are believed before
       the evidence is seen; putting the evidence first means the sentences land
       as a reading OF something rather than as the thing itself. */
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25, ease: "easeOut" }}
      className="mt-4 border-t-2 border-foreground pt-4"
    >
      <div className="flex flex-col gap-3.5">
        {/* ---------- MEASURED ---------- */}
        <section
          className="rounded-md border-2 border-foreground p-3.5"
          style={{ background: "var(--card-surface)", boxShadow: "3px 3px 0 0 #000" }}
        >
          <Tag source="measured" note="Our price snapshot, read off disk" />
          <div className="mt-2.5">
            <Figures facts={state.facts} />
          </div>
        </section>

        {/* ---------- LIVE MARKET ---------- */}
        {state.facts.graded ? (
          <section
            className="rounded-md border-2 p-3.5"
            style={{
              borderColor: "var(--pokemon-blue)",
              background: "color-mix(in srgb, var(--pokemon-blue) 6%, white)",
            }}
          >
            <Tag source="market" note="eBay, fetched for this card just now" />
            <Graded graded={state.facts.graded} />
          </section>
        ) : null}

        {/* ---------- WRITTEN BY AI ---------- */}
        <section
          className="rounded-md border-2 border-foreground p-3.5"
          style={{ background: "var(--card-surface)", boxShadow: "3px 3px 0 0 #000" }}
        >
          <div className="flex flex-wrap items-center justify-between gap-2">
            <Tag source="ai" note="No figures were given to it" />
            <button
              type="button"
              onClick={ask}
              className="text-[11px] font-black uppercase tracking-[0.06em] underline underline-offset-[3px]"
              style={{ color: "var(--pokemon-blue)" }}
            >
              Rewrite
            </button>
          </div>
          <div className="mt-3">
            <Rendered text={state.text} />
          </div>
        </section>

        {/* ---------- OUTSIDE OUR RECORDS ---------- */}
        {state.web ? (
          <section
            className="rounded-md border-2 border-dashed p-3.5"
            style={{ borderColor: "var(--pokemon-blue)" }}
          >
            <Tag source="outside" note="Searched the open web — we cannot check this" />
            <p className="mt-2.5 text-[13px] leading-[1.55]" style={{ color: "var(--pokemon-blue)" }}>
              {state.web}
            </p>
          </section>
        ) : null}

        {/* ---------- THE EXACT INPUT ---------- */}
        <details className="rounded-md border-2 border-dashed p-3" style={{ borderColor: "var(--border-subtle)" }}>
          <summary className="cursor-pointer list-none text-[10px] font-black uppercase tracking-[0.08em] text-muted-text">
            What the AI was told — the exact input
          </summary>
          <ul className="mt-2 grid gap-1">
            {state.facts.printings.map((print, index) => (
              <li key={index} className="flex items-baseline justify-between gap-2 text-[11px]">
                <span className="truncate">
                  {print.finish ?? "single printing"}
                  <span className="text-muted-text">
                    {" · "}
                    {print.origin}
                    {print.rarity ? ` · ${print.rarity}` : ""}
                  </span>
                </span>
                <span className="shrink-0 tabular-nums text-muted-text">
                  {print.cardmarketEur !== undefined ? `EUR ${print.cardmarketEur.toFixed(2)}` : ""}
                  {print.cardmarketEur !== undefined && print.tcgplayerUsd !== undefined ? " · " : ""}
                  {print.tcgplayerUsd !== undefined ? `USD ${print.tcgplayerUsd.toFixed(2)}` : ""}
                  {print.cardmarketEur === undefined && print.tcgplayerUsd === undefined ? "no figure" : ""}
                </span>
              </li>
            ))}
          </ul>
          <p className="mt-2 text-[10px] leading-relaxed text-muted-text">
            {/* THE STRONGEST CLAIM ON THIS PANEL, so it is stated where it can
                be checked rather than in marketing copy: the model is handed
                shapes, not figures — "near the bottom of its set", never 0.04 —
                so it cannot misquote a price it was never given. */}
            The AI receives none of these numbers. It is given shapes only — where the card sits in its set,
            how far apart the printings are — so it cannot misquote a figure it never had. It has no internet
            access and was told not to use anything it remembers about this card.
          </p>
        </details>
      </div>
    </motion.div>
  );
}
