#!/usr/bin/env -S UNUSED=1 npx tsx
/**
 * Regenerates docs/pipeline-pokemon.xlsx and docs/pipeline-one-piece.xlsx.
 *
 * WHY A GENERATOR. The first versions of these were written by hand, and by the
 * time the One Piece query model settled every figure in them was wrong —
 * catalogue sizes, call counts, the number of tracked cards, the shape of the
 * eBay query. A spreadsheet nobody can regenerate is a spreadsheet that quietly
 * stops being true.
 *
 * Everything measurable is read live from the code and the corpus at build
 * time: catalogue stats, price-snapshot sizes, the ref list, the budget
 * ceilings, the derived query for every tracked card. The prose rows are
 * constants here, so a claim can only go stale if someone edits this file.
 *
 * Reads only local files. No API calls, so it is free to run.
 *
 *   npm run docs:pipelines
 */
import { writeFileSync, rmSync, readFileSync } from "node:fs";
import { spawnSync } from "node:child_process";
import path from "node:path";

const { catalogStats } = await import("../src/lib/catalog");
const { opCatalogStats } = await import("../src/lib/one-piece-catalog");
const { cardRefs } = await import("../src/data/card-refs");
const { deriveQueryForCard, clause } = await import("../src/lib/one-piece-variants");
const { OP_SET_VOCABULARY, OP_PRODUCT_VOCABULARY } = await import("../src/data/one-piece-sets");
const { GRADED_MARKET_CONDITIONS, GRADED_MARKET_LANGUAGES } = await import("../src/lib/graded-market");

/**
 * The ceilings, restated here rather than imported.
 *
 * lib/api-budget.ts keeps BUDGETS private on purpose — it is the module that
 * enforces them, and exporting the table so a docs script can read it would
 * make it look editable from outside. These four lines are the only duplication
 * in this file, and check-one-piece-vocabulary.mts is the pattern for catching
 * the kind of drift that matters; a stale budget figure in a spreadsheet is not
 * that kind.
 */
const BUDGET_LINES: Record<string, string> = {
  "api.pokewallet.io#pokewallet": "60/hour",
  "api.pokewallet.io#berrywallet": "90/hour (real cap 100)",
  "api.apitcg.com": "900/month, burst 200/day",
  "api.ebay.com": "1200/day (real cap 5000)",
};

const pk = catalogStats();
const op = opCatalogStats();
const pokemonRefs = cardRefs.filter((r) => r.tcg === "pokemon");
const onePieceRefs = cardRefs.filter((r) => r.tcg === "one-piece");
const tiers = GRADED_MARKET_CONDITIONS.length * GRADED_MARKET_LANGUAGES.length;

function priceRows(file: string): { rows: number; generatedAt: string } {
  try {
    const j = JSON.parse(readFileSync(path.join(process.cwd(), "data", "prices", file), "utf8")) as {
      generatedAt?: string;
      cards?: Record<string, unknown>;
    };
    return { rows: Object.keys(j.cards ?? {}).length, generatedAt: (j.generatedAt ?? "").slice(0, 10) };
  } catch {
    return { rows: 0, generatedAt: "not generated" };
  }
}
const pkPrices = priceRows("pokemon.json");
const opPrices = priceRows("one-piece.json");

type Sheet = { name: string; rows: (string | number)[][] };

function budgetLine(bucket: string): string {
  return BUDGET_LINES[bucket] ?? "—";
}

const readMe = (franchise: string, extra: (string | number)[][]): Sheet => ({
  name: "Read me",
  rows: [
    [`${franchise} — how a card gets from a code to a priced page`],
    [""],
    ["Generated by", "npm run docs:pipelines"],
    ["Generated at", new Date().toISOString().slice(0, 10)],
    [""],
    ["Every number here is read from the code and the local corpus at generation"],
    ["time. Do not edit this file by hand — edit scripts/build-pipeline-docs.mts."],
    [""],
    ["Narrative companion", "docs/pipeline-by-franchise.md"],
    ["eBay query model", "docs/ebay-market-pipeline.md"],
    ["Adding a card", "docs/adding-a-card.md"],
    [""],
    ...extra,
  ],
});

// ---------------------------------------------------------------- Pokémon ----

const pokemon: Sheet[] = [
  readMe("Pokémon", [
    ["Catalogue sets", pk.sets],
    ["Catalogue cards", pk.cards],
    ["Cards with a Cardmarket pointer", pk.withCardmarketPointer],
    ["Cards with a TCGplayer pointer", pk.withTcgplayerPointer],
    ["Price snapshot rows", pkPrices.rows],
    ["Price snapshot generated", pkPrices.generatedAt],
    ["Cards tracked live", pokemonRefs.length],
  ]),
  {
    name: "Pipeline",
    rows: [
      ["#", "Step", "Source", "Cost", "Notes"],
      [1, "Identity", "data/catalog/pokemon (TCGdex crawl)", "0 calls", "Tier 1. name + set + number is a unique key."],
      [2, "Browse prices", "data/prices/pokemon.json", "0 calls", "Snapshot regenerated by npm run prebuild."],
      [3, "Live price", "apitcg", budgetLine("api.apitcg.com"), "Tracked cards only."],
      [4, "Price history", "apitcg", "shared", "BerryWallet has no history endpoint; apitcg serves both franchises."],
      [5, "EU / Cardmarket", "PokéWallet, stored id", budgetLine("api.pokewallet.io#pokewallet"), "pokeWalletWesternCardId on the ref."],
      [6, "JA identity", "PokéWallet, stored id", "1 call", "pokeWalletCardId. Hand-confirmed; see card-refs.ts."],
      [7, "FR text", "TCGdex /v2/fr", "0 calls", "Free and unmetered."],
      [8, "Graded market", "eBay Browse", budgetLine("api.ebay.com"), `${GRADED_MARKET_CONDITIONS.length} conditions x ${GRADED_MARKET_LANGUAGES.length} languages = ${tiers} searches per card.`],
    ],
  },
  {
    name: "Catalogue",
    rows: [
      ["Metric", "Value", "Notes"],
      ["Sets", pk.sets, "Digital-only (TCG Pocket) sets are excluded from browse and 404 on direct URL."],
      ["Cards", pk.cards, ""],
      ["Unresolved", pk.unresolved, "Cards the crawl could not read."],
      ["Cardmarket pointer", pk.withCardmarketPointer, `${((pk.withCardmarketPointer / pk.cards) * 100).toFixed(1)}% — read from BOTH places TCGdex stores it.`],
      ["TCGplayer pointer", pk.withTcgplayerPointer, `${((pk.withTcgplayerPointer / pk.cards) * 100).toFixed(1)}%`],
      ["Multi-variant cards", pk.multiVariant, "More than one printing under one id."],
      ["Crawled at", pk.crawledAt ?? "", ""],
      ["", "", ""],
      ["Rebuild", "npx tsx scripts/catalog-crawl.mts", "Resumable. TCGdex is free and unmetered."],
      ["Prices", "npm run prices", "Writes data/prices/pokemon.json."],
    ],
  },
  {
    name: "Rules and exceptions",
    rows: [
      ["Rule", "Why"],
      ["Tier 1 imports node:fs only", "A catalogue module that cannot reach an API cannot spend quota by mistake."],
      ["Prices never live in the catalogue", "Identity is stable and its diff should be readable; prices churn and carry a date."],
      ["Set pages are prerendered", "Safe only because the build makes no requests. An earlier attempt froze empty prices into static HTML for 24h."],
      ["Digital-only sets 404", "286 tiles all reading 'No price' is worse than an honest 404."],
      ["outputFileTracingIncludes", "Required, or the serverless bundle ships without the corpus and serves an empty catalogue."],
      ["A stated absence beats a blank", "'We do not price this printing' is a valid cell."],
    ],
  },
  {
    name: "Per card",
    rows: [
      ["Slug", "Character", "Lookup", "JP id stored", "Western id stored"],
      ...pokemonRefs.map((r) => [
        r.slug,
        r.character,
        r.lookup.by === "code" ? `code ${r.lookup.code}` : `${r.lookup.name} / ${r.lookup.setName} / ${r.lookup.number}`,
        r.pokeWalletCardId ? "yes" : "no",
        (r as { pokeWalletWesternCardId?: string }).pokeWalletWesternCardId ? "yes" : "no",
      ]),
    ],
  },
];

// -------------------------------------------------------------- One Piece ----

const opQueries = onePieceRefs.map((ref) => {
  if (ref.lookup.by !== "code") return [ref.slug, "", "", ""];
  const override = ref.ebayVariantTags?.en;
  const derived = deriveQueryForCard(ref.lookup.code, undefined, ref.lookup.variantTags);
  return [
    ref.slug,
    ref.lookup.code,
    override && override.length > 0 ? "hand-written override" : (derived?.treatment ?? "—"),
    `${ref.lookup.code} PSA 10 ${override && override.length > 0 ? clause(override) : (derived?.queryText ?? "—")}`,
  ];
});

const onePiece: Sheet[] = [
  readMe("One Piece", [
    ["Corpus sets", op.sets],
    ["Corpus rows", op.rows],
    ["Distinct card codes", op.codes],
    ["Price snapshot rows", opPrices.rows],
    ["Price snapshot generated", opPrices.generatedAt],
    ["Cards tracked live", onePieceRefs.length],
    ["Set families in the vocabulary", Object.keys(OP_SET_VOCABULARY).length],
    ["Products in the vocabulary", Object.keys(OP_PRODUCT_VOCABULARY).length],
  ]),
  {
    name: "Pipeline",
    rows: [
      ["#", "Step", "Source", "Cost", "Notes"],
      [1, "Identity", "data/catalog/one-piece (BerryWallet crawl)", "0 calls", "Tier 1. A code is an identity, not a printing."],
      [2, "Which printing", "corpus rows sharing the code", "0 calls", "Was a metered searchCards call per card."],
      [3, "Browse prices", "data/prices/one-piece.json", "0 calls", "Captured during the same crawl."],
      [4, "Live identity", "BerryWallet", budgetLine("api.pokewallet.io#berrywallet"), "Tracked cards only. Tightest quota in the system."],
      [5, "Price history", "apitcg", budgetLine("api.apitcg.com"), "BerryWallet has no history endpoint."],
      [6, "EU / Cardmarket", "corpus row, or a sibling on the shared TCGplayer product URL", "0 calls", "That URL is the only proof two rows are one card."],
      [7, "JA identity", "(V.N) alignment across languages", "varies", "REFUSED for a cross-product match — the index belongs to another product's tiering."],
      [8, "Graded market", "eBay Browse", budgetLine("api.ebay.com"), `${tiers} searches per card, query derived — see the Query model sheet.`],
    ],
  },
  {
    name: "Query model",
    rows: [
      ["Axis", "Answers", "Where it comes from", "Example"],
      ["Treatment", "which version", "closed vocabulary in one-piece-variants.ts", "(manga) / (alt,alternate,alternative,altart,parallel)"],
      ["Product", "which printing of that version", "src/data/one-piece-sets.ts", '(prb,"premium booster","the best") / -"2nd anniversary"'],
      ["Rarity", "whether it is this card at all", "corpus row rarity", "-uc -r -sec -l -tr -don"],
      ["Spelling", "what sellers actually type", "terms list per treatment", "altart, alternative, parallel"],
      ["", "", "", ""],
      ["Domain rules that no catalogue can supply", "", "", ""],
      ["Parallel = Alternate Art", "same treatment, two eras of naming", "no code carries both as separate rows", ""],
      ["Manga is a kind of Alt Art", "search the subtype alone", "naming both admits the plain Alt Art printing", ""],
      ["A Manga reprint keeps the artwork", "group OG and PRB-01", "medians $1,475 and $1,600 on OP05-074", ""],
      ["An Alt Art reprint does not", "split them", "$790 against $400 on OP05-119", ""],
    ],
  },
  {
    name: "Vocabulary",
    rows: [
      ["Kind", "Key", "Search terms", "Exclusion token"],
      ...Object.entries(OP_SET_VOCABULARY).map(([k, v]) => ["set family", k, v.terms.join(" | "), v.exclude ?? "(never)"]),
      ...Object.entries(OP_PRODUCT_VOCABULARY).map(([k, v]) => ["product", k, v.terms.join(" | "), v.exclude ?? "(never)"]),
      ["", "", "", ""],
      ["A missing entry fails the build", "npm run check:one-piece", "", ""],
    ],
  },
  {
    name: "Per card",
    rows: [["Slug", "Code", "Treatment", "PSA 10 query"], ...opQueries],
  },
  {
    name: "Upstream gaps",
    rows: [
      ["Card", "Missing", "Why", "Status"],
      ["monkey-d-luffy-st21-014", "EU + JA", "No sibling shares its TCGplayer product; the JA walk has no entry point", "Backfill requested upstream 2026-09-05"],
      ["monkey-d-luffy-op01-024", "JA", "PRB-01 has no The-Best-Non-English row for this code", "Nothing honest to pin"],
      ["monkey-d-luffy-op09-061", "JA name and art", "Cross-product match refuses (V.N) alignment", "Translation gap, not a data gap"],
      ["op09-061 / p-033", "JP images", "Real JP prints exist that we cannot locate", "Deferred"],
      ["", "", "", ""],
      ["Architectural", "", "", ""],
      ["buildCached", "caches upstream FAILURES as real results", "One exhausted window can freeze empty markets for a day", "Open"],
      ["API budget ledger", "over-counts", "Charges at attempt time, so Data-Cache hits count", "Open"],
      ["ST / LT", "no exclusion token", "Deck names describe their own contents", "By design, revisit if sellers use set codes"],
      ["Identity resolution", "still per-card human work", "", "optcgapi.com to be evaluated"],
    ],
  },
];

// ------------------------------------------------------------------ write ----

/**
 * Handed to Python, which owns the .xlsx writing.
 *
 * No npm spreadsheet library: the obvious one (`xlsx`/SheetJS) is deprecated on
 * npm and carries known advisories, and a docs generator is not worth a
 * supply-chain risk. openpyxl is standard, already present, and this script
 * fails with a clear install line if it is not.
 */
const payload = { pokemon, onePiece };
const dataFile = path.join(process.cwd(), "docs", ".pipeline-data.json");
writeFileSync(dataFile, JSON.stringify(payload, null, 1), "utf8");

const result = spawnSync("python", [path.join("scripts", "build-pipeline-docs.py")], {
  stdio: "inherit",
  cwd: process.cwd(),
});
rmSync(dataFile, { force: true });

if (result.status !== 0) {
  console.error(
    `
[docs] the workbook writer failed. It needs Python with openpyxl:
` +
      `       python -m pip install openpyxl
`
  );
  process.exit(1);
}
